version: "3.7"

services:

  gateway:
    container_name: gateway
    build: gateway
    networks:
      - ellaid-net
    ports:
      - "80:8080"

  eureka:
    container_name: eureka
    build: eureka
    networks:
      - ellaid-net
    ports:
      - "8761:8761"

  auth:
    container_name: auth
    build: auth
    networks:
      - ellaid-net
    ports:
      - "8081:8081"
    depends_on:
      - auth-mongodb
    environment:
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_EXPIRATION_TIME_MS: ${JWT_EXPIRATION_TIME_MS}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

  comment:
    container_name: comment
    build: comment
    networks:
      - ellaid-net
    ports:
      - "8082:8082"
    depends_on:
      - comment-mongodb
    environment:
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_EXPIRATION_TIME_MS: ${JWT_EXPIRATION_TIME_MS}

  playlist:
    container_name: playlist
    build: playlist
    networks:
      - ellaid-net
    ports:
      - "8083:8083"
    depends_on:
      - playlist-mongodb
    environment:
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_EXPIRATION_TIME_MS: ${JWT_EXPIRATION_TIME_MS}

  track:
    container_name: track
    build: track
    networks:
      - ellaid-net
    ports:
      - "8084:8084"
    depends_on:
      - track-mongodb
    environment:
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_EXPIRATION_TIME_MS: ${JWT_EXPIRATION_TIME_MS}

  storage:
    container_name: storage
    build: storage
    networks:
      - ellaid-net
    ports:
      - "8085:8085"
    depends_on:
      - minio
    environment:
      MINIO_URL: ${MINIO_URL}
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET: ${MINIO_BUCKET}
      HOST_URL: ${HOST_URL}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_EXPIRATION_TIME_MS: ${JWT_EXPIRATION_TIME_MS}

  auth-mongodb:
    container_name: auth-mongodb
    image: mongo:latest
    networks:
      - ellaid-net
    volumes:
      - auth_data:/data/db

  comment-mongodb:
    container_name: comment-mongodb
    image: mongo:latest
    networks:
      - ellaid-net
    volumes:
      - comment_data:/data/db

  playlist-mongodb:
    container_name: playlist-mongodb
    image: mongo:latest
    networks:
      - ellaid-net
    volumes:
      - playlist_data:/data/db

  track-mongodb:
    container_name: track-mongodb
    image: mongo:latest
    networks:
      - ellaid-net
    volumes:
      - track_data:/data/db

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - ellaid-net
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server --console-address ":9001" /data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - minio_storage:/data

networks:
  ellaid-net:

volumes:
  auth_data:
  comment_data:
  playlist_data:
  track_data:
  minio_storage:
