apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka
  labels:
    tier: eureka
    app: ellaid
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: eureka
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        tier: eureka
    spec:
      containers:
        - name: eureka
          image: denchkm/ellaid-eureka
          ports:
            - containerPort: 8761
              protocol: TCP
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
            requests:
              memory: "128Mi"
              cpu: "50m"