version: "3.7"

services:
  app:
    container_name: track-service
    build: .
    restart: always
    networks:
      - track-service-net
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    networks:
      - track-service-net
    ports:
      - "27017:27017"
    env_file:
      - .env.dev
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db

networks:
  track-service-net:

volumes:
  mongodb_data:
