version: "3.7"

services:
  app:
    container_name: standalone-playlist-service
    build: .
    restart: always
    networks:
      - playlist-service-net
    ports:
      - "8083:8083"
    depends_on:
      - mongodb
    environment:
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_EXPIRATION_TIME_MS: ${JWT_EXPIRATION_TIME_MS}

  mongodb:
    container_name: standalone-playlist-mongodb
    image: mongo:latest
    restart: always
    networks:
      - playlist-service-net
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

networks:
  playlist-service-net:

volumes:
  mongodb_data:
