apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment
  labels:
    tier: comment
    app: ellaid
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: comment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        tier: comment
    spec:
      containers:
        - name: comment
          image: denchkm/ellaid-comment
          envFrom:
            - configMapRef:
                name: comment-config
          ports:
            - containerPort: 8082
              protocol: TCP
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
            requests:
              memory: "128Mi"
              cpu: "50m"