apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    tier: gateway
spec:
  ports:
    - nodePort: 30239
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    tier: gateway
  type: NodePort