version: "3.7"

services:
  app:
    container_name: user-service
    build: .
    restart: always
    networks:
      - user-service-net
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  mongodb:
    container_name: user-mongodb
    image: mongo:latest
    restart: always
    networks:
      - user-service-net
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

networks:
  user-service-net:

volumes:
  mongodb_data:
