server.port: 8083

spring:
  application.name: playlist

  data:
    mongodb:
      uri: mongodb://playlist-mongodb:27017/playlist-service-db
      auto-index-creation: true

app:
  security:
    jwt-secret-key: ${JWT_SECRET_KEY}
    issuer: ${JWT_ISSUER}
    expiration-time-ms: ${JWT_EXPIRATION_TIME_MS}

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka
