spring:
  application.name: auth

  data:
    mongodb:
      host: auth-mongodb
      port: 27017
      database: auth-service-db
      auto-index-creation: true

app:
  security:
    jwt-secret-key: ${JWT_SECRET_KEY}

logging:
  level:
    org:
      springframework:
        security: DEBUG
