server.port: 8084

spring:
  application.name: track

  data:
    mongodb:
      host: track-mongodb
      port: 27017
      database: track-service-db
      auto-index-creation: true

app:
  security:
    jwt-secret-key: ${JWT_SECRET_KEY}
    issuer: ${JWT_ISSUER}
    expiration-time-ms: ${JWT_EXPIRATION_TIME_MS}

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka

search:
  return-limit: 5

metadata:
  update-period-ms: 10000
