apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
data:
  JWT_SECRET_KEY: "aahhahhahahahahpaphaphaphapahpahphahpahahahaahahhaahahaha"
  JWT_ISSUER: "me"
  JWT_EXPIRATION_TIME_MS: "100000000000"

  ADMIN_USERNAME: "admin"
  ADMIN_PASSWORD: "admin"

  EUREKA_URL: "http://eureka:8761/eureka"
